# Собственные значения и собственные вектора

Ненулевой вектор $v$ называется собственным вектором квадратной $n \times n$ матрицы $A$, если выполняется равенство $Av = \lambda v$, где $\lambda$ $-$ скаляр, называемый собственным значением матрицы $A$, соответствующим собственному вектору $v$.

Рассматриваемое выше равенство можно записать в виде однородной системы линейных уравнений $(A - \lambda E)v = 0$. Оно имеет нетривиальное решение только при $\vert A - \lambda E \vert = 0$ $-$ характеристическое уравнение матрицы. 

Это уравнение имеет ровно n корней (с учётом кратности): $(\lambda - \lambda_1)^{n_1} (\lambda - \lambda_2)^{n_2} \dots (\lambda - \lambda_m)^{n_m}$, где $n_1 + \dots n_m = n$

Для каждого собственного значения $\lambda_i$ решается отдельно уравнение на собственные векторы: $(A - \lambda_i E)v = 0$

Количество собственных векторов для собственного значения кратности $n_i$ $-$ $m_i$, при этом $m_i \leq n_i$.

Рассмотрим матрицу $A = \begin{pmatrix} 3 & -0.5 & -2\\ 0 & 2 & 0\\ 0 & 0 & 1 \end{pmatrix}$. 

Найдём её собственные значения: $\begin{vmatrix} 3 - \lambda & -0.5 & -2\\ 0 & 2 - \lambda & 0\\ 0 & 0 & 1 - \lambda \end{vmatrix} = (3 - \lambda)(2 - \lambda)(1 - \lambda)$.

Таким образом, получаем, что $\lambda_1 = 3, \lambda_2 = 2, \lambda_1 = 1$

Решая уравнения $(A - \lambda_i E)v = 0$ находим собственные векторы $v_1 = \begin{pmatrix} 1 \\ 0 \\ 0 \end{pmatrix}, v_2 = \begin{pmatrix} 1 \\ 2 \\ 0 \end{pmatrix}, v_3 = \begin{pmatrix} 1 \\ 0 \\ 1 \end{pmatrix}$

In [18]:
import numpy as np

In [39]:
A = np.array([[3., -0.5, -2], [0., 2., 0.], [0., 0., 1.]])
values, vectors = np.linalg.eig(A)
print('Собственные значения:')
print(values)
print("Собственные векторы:")
print(vectors)

Собственные значения:
[3. 2. 1.]
Собственные векторы:
[[1.         0.4472136  0.70710678]
 [0.         0.89442719 0.        ]
 [0.         0.         0.70710678]]


# Разложение матрицы по собственным векторам

<img src = "https://sun9-west.userapi.com/sun9-6/s/v1/ig2/I88rtetLmAxRj1GOx3M0f-pF5GDV-6CHhmaRhx4SZ1GrVrWu05tZ5lEVg0b-OZpGMu28JpAw2n47ViOZAs41KCbO.jpg?size=1387x457&quality=95&type=album">

Пусть дана матрица $A$ $-$ квадратная порядка $n$ и существует $n$ линейно независимых собственных векторов. Тогда матрица A представима в виде произведения трёх матриц $S \Lambda S^{-1}$, где $S$ $-$ матрица, где в качестве столбцов представлены собственные вектора матрицы $A$, $\Lambda$ $-$ диагональная матрица с соответствующими собственными значениями.

Пусть $\lambda_1, \dots, \lambda_n$ $-$ собственные значения матрицы $A$, а $v_1, \dots, v_n$ $-$ соответствующие линейно независимые собственные вектора.

Тогда $S = \begin{bmatrix} v_1 & v_2 & \cdots & v_n \end{bmatrix} = \begin{bmatrix} v_{11} & v_{21} & \cdots & v_{n1} \\ v_{12} & v_{22} & \cdots & v_{n2} \\ \vdots & \vdots & \ddots & \vdots \\ v_{1n} & v_{2n} & \cdots & v_{nn} \end{bmatrix} $

Тогда $AS = A \begin{bmatrix} v_1 & v_2 & \cdots & v_n \end{bmatrix} = \begin{bmatrix} Av_1 & Av_2 & \cdots & Av_n \end{bmatrix} = \begin{bmatrix} \lambda_1 v_1 & \lambda_2 v_2 & \cdots & \lambda_n v_n \end{bmatrix} = \begin{bmatrix} \lambda_1 v_{11} & \lambda_2 v_{21} & \cdots & \lambda_n v_{n1} \\ \lambda_1 v_{12} & \lambda_2 v_{22} & \cdots & \lambda_n v_{n2} \\ \vdots & \vdots & \ddots & \vdots \\ \lambda_1 v_{1n} & \lambda_2 v_{2n} & \cdots & \lambda_n v_{nn} \end{bmatrix} = \begin{bmatrix} v_{11} & v_{21} & \cdots & v_{n1} \\ v_{12} & v_{22} & \cdots & v_{n2} \\ \vdots & \vdots & \ddots & \vdots \\ v_{1n} & v_{2n} & \cdots & v_{nn} \end{bmatrix} \begin{bmatrix} \lambda_1 & 0 & \cdots & 0 \\ 0 & \lambda_2 & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \cdots & \lambda_n \end{bmatrix} = S \Lambda$

Таким образом, $A = S \Lambda S^{-1}$

*Замечание:* Если $A$ $-$ симметрическая, то $S$ $-$ ортогональная.

In [51]:
def spectral_decomposition(X):
    values, S = np.linalg.eig(X)
    return S, np.diag(values), np.linalg.inv(S)

In [52]:
S, L, S_1 = spectral_decomposition(A)
print("S:", S, sep = "\n")
print("L:", L, sep = "\n")
print("S_1:", S_1, sep = "\n")

S:
[[1.         0.4472136  0.70710678]
 [0.         0.89442719 0.        ]
 [0.         0.         0.70710678]]
L:
[[3. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]
S_1:
[[ 1.         -0.5        -1.        ]
 [ 0.          1.11803399  0.        ]
 [ 0.          0.          1.41421356]]


In [53]:
print(S.dot(L).dot(S_1))

[[ 3.  -0.5 -2. ]
 [ 0.   2.   0. ]
 [ 0.   0.   1. ]]


# Зачем это нужно?

Рассмотрим $A^2 = (S \Lambda S^{-1})^2 = (S \Lambda S^{-1})(S \Lambda S^{-1}) = S \Lambda S^{-1} (S^{-1} S) \Lambda S^{-1} = S \Lambda^2 S^{-1}$

Таким образом по индукции получаем, что $A^n = S \Lambda^n S^{-1}$, где $\Lambda^n = \begin{bmatrix} \lambda_1^n & 0 & \cdots & 0 \\ 0 & \lambda_2^n & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \cdots & \lambda_k^n \end{bmatrix}$

Если ни одно из собственных значений не равно нулю, то $A^{-1} = (S \Lambda S^{-1})^{-1} = S \Lambda^{-1} S^{-1}$, где $\Lambda^{-1} = \begin{bmatrix} \lambda_1^{-1} & 0 & \cdots & 0 \\ 0 & \lambda_2^{-1} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \cdots & \lambda_k^{-1} \end{bmatrix}$

Также с помощью спектрального разложения можно получить матричную экспоненту: 

$e^A = \sum\limits_{n=0}^{\infty} \frac{A^n}{n!} = \sum\limits_{n=0}^{\infty} \frac{S \Lambda^n S^{-1}}{n!} = S (\sum\limits_{n=0}^{\infty} \frac{\Lambda^n}{n!}) S^{-1} = S e^D S^{-1}$,

где $e^D = \sum\limits_{n=0}^{\infty} \frac{D^n}{n!} = \sum\limits_{n=0}^{\infty} \frac{1}{n!} \begin{bmatrix} \lambda_1^n & 0 & \cdots & 0 \\ 0 & \lambda_2^n & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \cdots & \lambda_n^n \end{bmatrix} = \begin{bmatrix} \sum\limits_{n=0}^{\infty} \frac{\lambda_1^n}{n!} & 0 & \cdots & 0 \\ 0 & \sum\limits_{n=0}^{\infty} \frac{\lambda_2^n}{n!} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \cdots & \sum\limits_{n=0}^{\infty} \frac{\lambda_k^n}{n!} \end{bmatrix} = \begin{bmatrix} e^{\lambda_1^n} & 0 & \cdots & 0 \\ 0 & e^{\lambda_2^n} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \cdots & e^{\lambda_n^n} \end{bmatrix}$

In [62]:
print(np.linalg.matrix_power(A, 50))
print()
print(S.dot(L ** 50).dot(S_1))

[[ 7.17897988e+23 -3.58948993e+23 -7.17897988e+23]
 [ 0.00000000e+00  1.12589991e+15  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]

[[ 7.17897988e+23 -3.58948993e+23 -7.17897988e+23]
 [ 0.00000000e+00  1.12589991e+15  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [64]:
print(np.linalg.inv(A))
print()
print(S.dot(np.diag(np.diagonal(L) ** (-1))).dot(S_1))

[[0.33333333 0.08333333 0.66666667]
 [0.         0.5        0.        ]
 [0.         0.         1.        ]]

[[0.33333333 0.08333333 0.66666667]
 [0.         0.5        0.        ]
 [0.         0.         1.        ]]


In [70]:
from scipy.linalg import expm

print(expm(A))
print()
print(S.dot(np.diag(np.exp(np.diagonal(L)))).dot(S_1))

[[ 20.08553692  -6.34824041 -17.36725509]
 [  0.           7.3890561    0.        ]
 [  0.           0.           2.71828183]]

[[ 20.08553692  -6.34824041 -17.36725509]
 [  0.           7.3890561    0.        ]
 [  0.           0.           2.71828183]]
